store/storeapp/Areas/Admin/Controllers/ProductController.cs
using Entities.Dtos;
using Entities.Models;
using Entities.RequestParameters;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Services.Contracts;
using StoreApp.Models;

namespace StoreApp.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles ="Admin")]
    public class ProductController : Controller
    {
        private readonly IServiceManager _manager;

        public ProductController(IServiceManager manager)
        {
            _manager = manager;
        }

        public IActionResult Index([FromQuery] ProductRequestParameters p)
        {
            ViewData["Title"] = "Products";

            var products = _manager.ProductService.GetAllProductsWithDetails(p);
            var pagination = new Pagination()
            {
                CurrenPage = p.PageNumber,
                ItemsPerPage = p.PageSize,
                TotalItems = _manager.ProductService.GetAllProducts(false).Count()
            };
            return View(new ProductListViewModel()
            {
                Products = products,
                Pagination = pagination
            });
        }

        public IActionResult Create()
        {
            TempData["info"] = "Please fill the form.";
            ViewBag.Categories = GetCategoriesSelectList();
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([FromForm] ProductDtoForInsertion productDto, IFormFile file)
        {
            if (ModelState.IsValid)
            {
                // file operation
                string path = Path.Combine(Directory.GetCurrentDirectory(),
                "wwwroot","images",file.FileName);

                using (var stream = new FileStream(path,FileMode.Create))
                {
                    await file.CopyToAsync(stream);
                }
                productDto.ImageUrl = String.Concat("/images/",file.FileName);
                _manager.ProductService.CreateProduct(productDto);
                TempData["success"] = $"{productDto.ProductName} has been created.";
                return RedirectToAction("Index");
            }
            return View();
        }
        private SelectList GetCategoriesSelectList()
        {
            return new SelectList(_manager.CategoryService.GetAllCategories(false),
            "CategoryId",
            "CategoryName", "1");
        }


        public IActionResult Update([FromRoute(Name = "id")] int id)
        {
            ViewBag.Categories = GetCategoriesSelectList();
            var model = _manager.ProductService.GetOneProductForUpdate(id, false);
            ViewData["Title"] = model?.ProductName;
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Update([FromForm] ProductDtoForUpdate productDto, IFormFile file)
        {
            if (ModelState.IsValid)
            {
                // file operation
                string path = Path.Combine(Directory.GetCurrentDirectory(),
                "wwwroot","images",file.FileName);

                using (var stream = new FileStream(path,FileMode.Create))
                {
                    await file.CopyToAsync(stream);
                }
                productDto.ImageUrl = String.Concat("/images/",file.FileName);

                _manager.ProductService.UpdateOneProduct(productDto);
                return RedirectToAction("Index");
            }
            return View();
        }


        [HttpGet]
        public IActionResult Delete([FromRoute(Name = "id")] int id)
        {
            _manager.ProductService.DeleteOneProduct(id);
            TempData["danger"] = "The product has been removed.";
            return RedirectToAction("Index");
        }
    }
}

store/storeapp/Components/CategoriesMenuViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Services.Contracts;

namespace StoreApp.Components
{
    public class CategoriesMenuViewComponent : ViewComponent
    {
        private readonly IServiceManager _manager;

        public CategoriesMenuViewComponent(IServiceManager manager)
        {
            _manager = manager;
        }

        public IViewComponentResult Invoke()
        {
            var categories = _manager.CategoryService.GetAllCategories(false);
            return View(categories);
        }
    }
}

store/storeapp/Components/ProductFilterMenuViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace StoreApp.Components
{
    public class ProductFilterMenuViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            return View();
        }
    }
}

store/storeapp/Controllers/ProductController.cs
using Entities.Models;
using Entities.RequestParameters;
using Microsoft.AspNetCore.Mvc;
using Repositories;
using Repositories.Contracts;
using Services.Contracts;

namespace StoreApp.Controllers
{
    public class ProductController : Controller
    {
        private readonly IServiceManager _manager;

        public ProductController(IServiceManager manager)
        {
            _manager = manager;
        }

        public IActionResult Index(ProductRequestParameters p)
        {
            var model =  _manager.ProductService.GetAllProductsWithDetails(p);
            return View(model);
        }

        public IActionResult Get([FromRoute(Name="id")] int id)
        {
            var model = _manager.ProductService.GetOneProduct(id, false);
            return View(model);
        }
    }
}

store/storeapp/Areas/Admin/Views/Product/Create.cshtml
@model ProductDtoForInsertion

<div class="text-center">
    <div class="display-6">Create</div>
</div>

<form method="post" asp-action="Create" enctype="multipart/form-data">
    <div class="text-danger" asp-validation-summary="All"></div>

    <div class="form-group my-3">
        <label asp-for="CategoryId"></label>
        <select class="form-control" asp-items="@ViewBag.Categories" asp-for="CategoryId">
        </select>
    </div>

    <div class="form-group my-3">
        <label asp-for="ProductName"></label>
        <input asp-for="ProductName" class="form-control" />
    </div>

    <div class="form-group my-3">
        <label asp-for="Price"></label>
        <input asp-for="Price" class="form-control" />
    </div>

    <div class="form-group my-3">
        <label asp-for="Summary"></label>
        <input asp-for="Summary" class="form-control" />
    </div>

    <div class="form-group my-3">
        <label asp-for="ImageUrl"></label>
        <input name="file" type="file" class="form-control" />
    </div>

    <div class="form-group my-3">
        <div class="btn-group">
            <button type="submit">
                <i class="fa fa-save"></i>
                Save
            </button>
            <a asp-action="Index" class="btn btn-outline-primary">
                <i class="fa fa-list"></i>
                Products
            </a>
        </div>
    </div>
</form>

store/storeapp/Areas/Admin/Views/Product/Index.cshtml
@model ProductListViewModel

<div class="text-center">
    <div class="display-6">Products</div>

    <div class="d-flex justify-content-end my-3">
        <a class="btn btn-outline-success" asp-action="Create">
            <i class="fa fa-plus"></i>
            Create
        </a>
    </div>

    <div class="row">
        <div class="col-md-3">
            @await Component.InvokeAsync("CategoriesMenu")
            @await Component.InvokeAsync("ProductFilterMenu")
            <div products="" number="3"></div>
        </div>
        <div class="col-md-9">
            <table class="table table-striped table-hover">
                <thead>
                    <tr>
                        <th>Id</th>
                        <th>Product Name</th>
                        <th>ShowCase</th>
                        <th>Price</th>
                        <th>İmages</th>
                        <th>Summary</th>
                        <th>Category</th>
                        <th>Operations</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (Product prd in Model.Products)
                    {
                        <tr>
                            <td>@prd.ProductId</td>
                            <td>@prd.ProductName</td>
                            <td>
                                <div class="form-check form-switch">
                                    <input type="checkbox" class="form-check-input" checked="@prd.ShowCase" disabled />
                                </div>
                            </td>
                            <td>@prd.Price.ToString("c")</td>
                            <td><img class="border border-dark rounded" src="@prd?.ImageUrl" alt=""
                                    style="width: 7rem; height: 7rem;"></td>
                            <td>@prd.Summary</td>
                            <td>
                                @switch (prd.CategoryId)
                                {
                                    case 1:
                                        <span class="badge bg-primary">Book</span>
                                        break;
                                    case 2:
                                        <span class="badge bg-success">Electronic</span>
                                        break;
                                }
                            </td>
                            <td>
                                <div class="btn-group">
                                    <a data-toogle="tooltip" data-placement="top" title="Edit" class="btn btn-warning"
                                        asp-action="Update" asp-route-id="@prd.ProductId">
                                        <i class="fa fa-edit"></i>
                                        Edit</a>
                                    <a data-toogle="tooltip" data-placement="top" title="Delete" class="btn btn-danger"
                                        asp-action="Delete" asp-route-id="@prd.ProductId">
                                        <i class="fa fa-trash"></i>
                                        Delete</a>
                                    <a data-toogle="tooltip" data-placement="top" title="Web" class="btn btn-info"
                                        target="_blank" asp-area="" asp-controller="Product" asp-action="Get"
                                        asp-route-id="@prd.ProductId">
                                        <i class="fa fa-search"></i>
                                        Web</a>
                                </div>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

@section Scripts
{
    <script type="text/javascript">
        $(document).ready(() => {
            $('[data-toggle="tooltip"]').tooltip();
        });
    </script>
}

store/storeapp/Areas/Admin/Views/Product/Update.cshtml
@model ProductDtoForUpdate

<div class="text-center">
    <div class="display-6">Create</div>
</div>

<form method="post" asp-action="Update" enctype="multipart/form-data">
    <div class="text-danger" asp-validation-summary="All"></div>

    <input type="hidden" asp-for="ProductId" />

    <div class="form-group my-3">
        <label asp-for="CategoryId"></label>
        <select class="form-control" asp-items="@ViewBag.Categories" asp-for="CategoryId">
        </select>
    </div>

    <div class="form-group my-3">
        <label asp-for="ProductName"></label>
        <input asp-for="ProductName" class="form-control" />
    </div>

    <div class="form-group my-3">
        <label asp-for="Summary"></label>
        <input asp-for="Summary" class="form-control" />
    </div>


    <div class="form-group my-3">
        <label asp-for="Price"></label>
        <input asp-for="Price" class="form-control" />
    </div>

    <div class="form-group my-3">
        <img class="rounded shadow" src="@Model?.ImageUrl" style="width: 10rem;" />
    </div>

    <div class="form-group my-3">
        <label asp-for="ImageUrl"></label>
        <input type="file" name="file" class="form-control" />
    </div>

    <div class="form-group py-3 my-3">
        <div class="btn-group">
            <button type="submit">
                <i class="fa fa-save"></i>
                Update
            </button>
            <a asp-action="Index" class="btn btn-outline-primary">
                <i class="fa fa-list"></i>
                Products
            </a>
        </div>
    </div>
</form>