store/storeapp/Components/CartSummaryViewComponent.cs
using Entities.Models;
using Microsoft.AspNetCore.Mvc;

namespace StoreApp.Components
{
    public class CartSummaryViewComponent : ViewComponent
    {
        private readonly Cart _cart;
        public CartSummaryViewComponent(Cart cartService)
        {
            _cart = cartService;
        }

        public string Invoke()
        {
            return _cart.Lines.Count().ToString();
        }
    }
}

store/storeapp/Components/ProductSummaryViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Repositories;
using Services.Contracts;

namespace StoreApp.Component
{
    public class ProductSummaryViewComponent : ViewComponent
    {
        private readonly IServiceManager _manager;

        public ProductSummaryViewComponent(IServiceManager manager)
        {
            _manager = manager;
        }

        public string Invoke()
        {
            return _manager.ProductService.GetAllProducts(false).Count().ToString();
        }
    }
}

store/storeapp/Controllers/CategoryController.cs
using Entities.Models;
using Microsoft.AspNetCore.Mvc;
using Repositories.Contracts;

namespace StoreApp.Controllers
{
    public class CategoryController : Controller
    {
        private IRepositoryManager _manager;

        public CategoryController(IRepositoryManager manager)
        {
            _manager = manager;
        }

        public IActionResult Index()
        {
            var model =  _manager.Category.FindAll(false);
            return View(model);
        }
    }
}

store/storeapp/Controllers/ProductController.cs
using Entities.Models;
using Entities.RequestParameters;
using Microsoft.AspNetCore.Mvc;
using Repositories;
using Repositories.Contracts;
using Services.Contracts;

namespace StoreApp.Controllers
{
    public class ProductController : Controller
    {
        private readonly IServiceManager _manager;

        public ProductController(IServiceManager manager)
        {
            _manager = manager;
        }

        public IActionResult Index(ProductRequestParameters p)
        {
            var model =  _manager.ProductService.GetAllProductsWithDetails(p);
            return View(model);
        }

        public IActionResult Get([FromRoute(Name="id")] int id)
        {
            var model = _manager.ProductService.GetOneProduct(id, false);
            return View(model);
        }
    }
}

store/storeapp/Views/Shared/_Footer.cshtml
<div class="bg-light border-top p-3">
    <div>
        <div class="row">
            <div class="col-md-2">
                <div class="lead text-center ">
                    <bold>TrTek</bold>
                </div>
            </div>
            <div class="col-md-8">
                <div class="text-center">
                    <div class="btn-group">
                        <a class="btn btn-secondary">
                        </a>
                        <a class="btn btn-secondary">
                            <i class="fa-brands fa-twitter"></i>
                        </a>
                        <a class="btn btn-secondary">
                            <i class="fa-brands fa-linkedin"></i>
                        </a>
                        <a class="btn btn-secondary">
                            <i class="fa-brands fa-youtube"></i>
                        </a>
                        <a class="btn btn-secondary">
                            <i class="fa-brands fa-instagram"></i>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

store/storeapp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>TrTek</title>
    <link rel="stylesheet" href="~/lib/bootstrap/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/lib/font-awesome/css/all.css" />
</head>

<body>
    <header>
        <partial name="_Navbar" />
        @RenderSection("Header",false)
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <footer>
        @RenderSection("Footer",false)
        <partial name="_Footer" />
    </footer>
    <script src="~/lib/jquery/jquery.min.js"></script>
    <script src="~/lib/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js"></script>
    <script src="~/lib/font-awesome/js/all.min.js"></script>
    @await RenderSectionAsync("Scripts",required:false)
</body>

</html>

store/storeapp/Views/Shared/_LoginMenu.cshtml
@if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
{
<li>
    <a class="nav-link" aria-current="page" asp-area="Admin" asp-controller="Dashboard" asp-action="Index">
        <i class="fa-solid fa-gear"></i>
        Admin</a>
</li>
}

@if (User.Identity.IsAuthenticated)
{
    <li>
        <a class="nav-link" aria-current="page" asp-area="" asp-controller="Account" asp-route-returnUrl="@Context.Request.PathAndQuery()" asp-action="Logout">
            <i class="fa-solid fa-right-to-bracket"></i>
            Logout</a>
    </li>
}

else
{
    <li>
        <a class="nav-link" aria-current="page" asp-area="" asp-controller="Account" asp-route-returnUrl="@Context.Request.PathAndQuery()" asp-action="Login">
            <i class="fa-solid fa-right-to-bracket"></i>
            Login</a>
    </li>
}

store/storeapp/Views/Shared/_Navbar.cshtml
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <!-- Container wrapper -->
    <div class="container-fluid">
        <a class="navbar-brand" asp-controller="Home" asp-action="Index">
            <i class="fa-solid fa-store fa-2x text-secondary"></i>
            TrTek</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText"
            aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <!-- Collapsible wrapper -->
        <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between" id="navbarNavAltMarkup">
            <!-- Left links -->
            <ul class="navbar-nav flex-grow-1">
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Product" asp-action="Index">Products (@await Component.InvokeAsync("ProductSummary"))</a>
                </li>
                <!-- Navbar dropdown -->
                <li class="nav-item">
                    <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
                </li>
                <li>
                    <a class="nav-link active" aria-current="page" asp-controller="Category"
                        asp-action="Index">Categories</a>
                </li>
                <li>
                    <a class="nav-link active" aria-current="page" asp-page="/Contact">Contact</a>
                </li>
            </ul>
            <ul class="navbar-nav">
                <li>
                    <a class="nav-link" aria-current="page" asp-area="" asp-page="/Cart">
                    <i class="fa-solid fa-cart-shopping"></i>
                    Cart (@await Component.InvokeAsync("CartSummary"))  
                    </a>
                </li>

                <partial name="_LoginMenu" />
            </ul>
            <!-- Left links -->
        </div>
        <!-- Collapsible wrapper -->
    </div>
    <!-- Container wrapper -->
</nav>
<a href=""></a>

store/storeapp/Views/Shared/_ProductCard.cshtml
@model Product

<div class="col-sm-12 col-md-4 my-2">
    <div class="card" style="width: 18rem;">
        <div class="card-header text-center">
            @Model.ProductName
        </div>
        <img src="@Model?.ImageUrl" class="card-img-top" alt="...">

        <div class="card-body">
            <div class="card-text">
                <div class="text-danger text-center lead p-2 rounded-2">
                    @Model?.Price.ToString("C2")
                </div>
            </div>
        </div>
        <div class="card-body">
            <p class="card-text">@Model?.Summary</p>
            <div class="d-flex justify-content-center">
                <div class="btn btn-group">
                    <a asp-controller="Product" asp-action="Get" asp-route-id="@Model.ProductId"
                        class="btn btn-outline-secondary rounded-2">
                        <i class="fa-solid fa-arrow-right"></i>
                    </a>

                    <form id="@Model.ProductId" asp-page="/cart" method="post">
                        <input type="hidden" asp-for="ProductId" />
                        <input type="hidden" name="returnUrl" value="@ViewContext.HttpContext.Request.PathAndQuery()" />
                        <button type="submit" class="btn btn-outline-secondary mx-1">
                            <i class="fa fa-cart-plus"></i>
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>